[api_keys]
anthropic = "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"
openai = "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"
anyscale = "esecret_ew36yxzf6mkd4y9bcbtr6rznup"